name:                convert2png
version:             0.1.0.0
github:              "meloidae/convert2png"
license:             MIT
author:              "meloidae"
maintainer:          "example@example.com"
copyright:           "2021 meloidae"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/convert2png#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- JuicyPixels

library:
  source-dirs: src

executables:
  convert2png-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convert2png

tests:
  convert2png-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convert2png
